services:
  django:
    container_name: django
    build: ./requirements/django
    ports:
      - 8000:8000
    restart: always
    networks:
      - docker_network
    env_file:
      - .env
    volumes:
      - ./requirements/django:/code
    depends_on:
      postgres:
        condition: service_healthy
  
  postgres:
    container_name: postgres
    build: ./requirements/postgres
    ports:
      - 5432
    restart: always
    networks:
      - docker_network
    env_file:
      - .env
    environment:
      TZ: ${TZ}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  docker_network:

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./requirements/postgres/data